from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class PeopleSearchQuery(BaseModel):
    person_titles: Optional[List[str]] = Field(default=None, description="Job titles held by the people you want to find. For a person to be included in search results, they only need to match 1 of the job titles you add. Adding more job titles expands your search results. Results also include job titles with the same terms, even if they are not exact matches. For example, searching for `marketing manager` might return people with the job title `content marketing manager`. Use this parameter in combination with the `person_seniorities[]` parameter to find people based on specific job functions and seniority levels. Examples: `sales development representative`; `marketing manager`; `research analyst`")
    include_similar_titles: Optional[bool] = Field(default=True, description="This parameter determines whether people with job titles similar to the titles you define in the `person_titles[]` parameter are returned in the response. Set this parameter to `false` when using `person_titles[]` to return only strict matches for job titles.")
    person_locations: Optional[List[str]] = Field(default=None, description="The location where people live. You can search across cities, US states, and countries. To find people based on the headquarters locations of their current employer, use the `organization_locations` parameter. Examples: `california`; `ireland`; `chicago`")
    person_seniorities: Optional[List[str]] = Field(default=None, description="The job seniority that people hold within their current employer. This enables you to find people that currently hold positions at certain reporting levels, such as Director level or senior IC level. For a person to be included in search results, they only need to match 1 of the seniorities you add. Adding more seniorities expands your search results. Searches only return results based on their current job title, so searching for Director-level employees only returns people that currently hold a Director-level title. If someone was previously a Director, but is currently a VP, they would not be included in your search results. Use this parameter in combination with the `person_titles[]` parameter to find people based on specific job functions and seniority levels. The following options can be used for this parameter: `owner`, `founder`, `c_suite`, `partner`, `vp`, `head`, `director`, `manager`, `senior`, `entry`, `intern`")
    organization_locations: Optional[List[str]] = Field(default=None, description="The location of the company headquarters for a person's current employer. You can search across cities, US states, and countries. If a company has several office locations, results are still based on the headquarters location. For example, if you search `chicago` but a company's HQ location is in `boston`, people that work for the Boston-based company will not appear in your results, even if they match other parameters. To find people based on their personal location, use the `person_locations` parameter. Examples: `texas`; `tokyo`; `spain`")
    organization_industries: Optional[List[str]] = Field(default=None, description="The industries to which the person's current employer belongs. This enables you to find people based on the industry of their employer. You can add multiple industries to expand your search results. Examples: `financial services`; `banking`; `investment banking`; `investment management`")
    q_organization_keyword_tags: Optional[List[str]] = Field(default=None, description="The keyword tags associated with a person's current employer. This enables you to find people based on the keyword tags associated with their employer. You can add multiple keyword tags to expand your search results. Examples: `cloud computing`; `artificial intelligence`; `cybersecurity`")
    q_organization_domains_list: Optional[List[str]] = Field(default=None, description="The domain name for the person's employer. This can be the current employer or a previous employer. Do not include `www.`, the `@` symbol, or similar. This parameter accepts up to 1,000 domains in a single request. Examples: `apollo.io`; `microsoft.com`")
    contact_email_status: Optional[List[str]] = Field(default=None, description="The email statuses for the people you want to find. You can add multiple statuses to expand your search. The statuses you can search include: `verified`, `unverified`, `likely to engage`, `unavailable`")
    organization_ids: Optional[List[str]] = Field(default=None, description="The Apollo IDs for the companies (employers) you want to include in your search results. Each company in the Apollo database is assigned a unique ID. To find IDs, call the [Organization Search endpoint](/reference/organization-search) and identify the values for `organization_id`. Example: `5e66b6381e05b4008c8331b8`")
    organization_num_employees_ranges: Optional[List[str]] = Field(default=None, description="The number range of employees working for the person's current company. This enables you to find people based on the headcount of their employer. You can add multiple ranges to expand your search results. Each range you add needs to be a string, with the upper and lower numbers of the range separated only by a comma. Examples: `1,10`; `250,500`; `10000,20000`")
    q_keywords: Optional[str] = Field(default=None, description="A string of words over which we want to filter the results.")
    page: Optional[int] = Field(default=None, description="The page number of the Apollo data that you want to retrieve. Use this parameter in combination with the `per_page` parameter to make search results for navigable and improve the performance of the endpoint. Example: `4`")
    per_page: Optional[int] = Field(default=None, description="The number of search results that should be returned for each page. Limited the number of results per page improves the endpoint's performance. Use the `page` parameter to search the different pages of data. Example: `10`")

class Breadcrumb(BaseModel):
    label: str = Field(description="label")
    signal_field_name: str = Field(description="signal_field_name")
    value: str = Field(description="value")
    display_name: str = Field(description="display_name")

class DialerFlags(BaseModel):
    country_name: str = Field(description="country_name")
    country_enabled: bool = Field(description="country_enabled")
    high_risk_calling_enabled: bool = Field(description="high_risk_calling_enabled")
    potential_high_risk_number: bool = Field(description="potential_high_risk_number")

class PhoneNumber(BaseModel):
    raw_number: str = Field(description="raw_number")
    sanitized_number: str = Field(description="sanitized_number")
    type: str = Field(description="type")
    position: int = Field(description="position")
    status: str = Field(description="status")
    dnc_status: str = Field(description="dnc_status")
    dnc_other_info: str = Field(description="dnc_other_info")
    dialer_flags: DialerFlags = Field(description="dialer_flags")

class ContactEmail(BaseModel):
    email: str = Field(description="email")
    email_md5: str = Field(description="email_md5")
    email_sha256: str = Field(description="email_sha256")
    email_status: str = Field(description="email_status")
    email_source: str = Field(description="email_source")
    extrapolated_email_confidence: str = Field(description="extrapolated_email_confidence")
    position: int = Field(description="position")
    email_from_customer: str = Field(description="email_from_customer")
    free_domain: bool = Field(description="free_domain")

class Account(BaseModel):
    id: str = Field(description="id")
    name: str = Field(description="name")
    website_url: str = Field(description="website_url")
    blog_url: str = Field(description="blog_url")
    angellist_url: str = Field(description="angellist_url")
    linkedin_url: str = Field(description="linkedin_url")
    twitter_url: str = Field(description="twitter_url")
    facebook_url: str = Field(description="facebook_url")
    primary_phone: Dict[str, Any] = Field(description="primary_phone")
    languages: List[Any] = Field(description="languages")
    alexa_ranking: int = Field(description="alexa_ranking")
    phone: str = Field(description="phone")
    linkedin_uid: str = Field(description="linkedin_uid")
    founded_year: int = Field(description="founded_year")
    publicly_traded_symbol: str = Field(description="publicly_traded_symbol")
    publicly_traded_exchange: str = Field(description="publicly_traded_exchange")
    logo_url: str = Field(description="logo_url")
    crunchbase_url: str = Field(description="crunchbase_url")
    primary_domain: str = Field(description="primary_domain")
    domain: str = Field(description="domain")
    team_id: str = Field(description="team_id")
    organization_id: str = Field(description="organization_id")
    account_stage_id: str = Field(description="account_stage_id")
    source: str = Field(description="source")
    original_source: str = Field(description="original_source")
    creator_id: str = Field(description="creator_id")
    owner_id: str = Field(description="owner_id")
    created_at: str = Field(description="created_at")
    phone_status: str = Field(description="phone_status")
    hubspot_id: str = Field(description="hubspot_id")
    salesforce_id: str = Field(description="salesforce_id")
    crm_owner_id: str = Field(description="crm_owner_id")
    parent_account_id: str = Field(description="parent_account_id")
    sanitized_phone: str = Field(description="sanitized_phone")
    account_playbook_statuses: List[Any] = Field(description="account_playbook_statuses")
    account_rule_config_statuses: List[Any] = Field(description="account_rule_config_statuses")
    existence_level: str = Field(description="existence_level")
    label_ids: List[str] = Field(description="label_ids")
    typed_custom_fields: Dict[str, Any] = Field(description="typed_custom_fields")
    custom_field_errors: Dict[str, Any] = Field(description="custom_field_errors")
    modality: str = Field(description="modality")
    source_display_name: str = Field(description="source_display_name")
    salesforce_record_url: str = Field(description="salesforce_record_url")
    crm_record_url: str = Field(description="crm_record_url")

class EmploymentHistory(BaseModel):
    id: str = Field(description="id")
    created_at: str = Field(description="created_at")
    current: bool = Field(description="current")
    degree: str = Field(description="degree")
    description: str = Field(description="description")
    emails: str = Field(description="emails")
    end_date: str = Field(description="end_date")
    grade_level: str = Field(description="grade_level")
    kind: str = Field(description="kind")
    major: str = Field(description="major")
    organization_id: str = Field(description="organization_id")
    organization_name: str = Field(description="organization_name")
    raw_address: str = Field(description="raw_address")
    start_date: str = Field(description="start_date")
    title: str = Field(description="title")
    updated_at: str = Field(description="updated_at")
    id: str = Field(description="id")
    key: str = Field(description="key")

class Organization(BaseModel):
    id: str = Field(description="id")
    name: str = Field(description="name")
    website_url: str = Field(description="website_url")
    blog_url: str = Field(description="blog_url")
    angellist_url: str = Field(description="angellist_url")
    linkedin_url: str = Field(description="linkedin_url")
    twitter_url: str = Field(description="twitter_url")
    facebook_url: str = Field(description="facebook_url")
    primary_phone: Dict[str, Any] = Field(description="primary_phone")
    languages: List[Any] = Field(description="languages")
    alexa_ranking: int = Field(description="alexa_ranking")
    phone: str = Field(description="phone")
    linkedin_uid: str = Field(description="linkedin_uid")
    founded_year: int = Field(description="founded_year")
    publicly_traded_symbol: str = Field(description="publicly_traded_symbol")
    publicly_traded_exchange: str = Field(description="publicly_traded_exchange")
    logo_url: str = Field(description="logo_url")
    crunchbase_url: str = Field(description="crunchbase_url")
    primary_domain: str = Field(description="primary_domain")

class Contact(BaseModel):
    contact_roles: List[Any] = Field(description="contact_roles")
    id: str = Field(description="id")
    first_name: str = Field(description="first_name")
    last_name: str = Field(description="last_name")
    name: str = Field(description="name")
    linkedin_url: str = Field(description="linkedin_url")
    title: str = Field(description="title")
    contact_stage_id: str = Field(description="contact_stage_id")
    owner_id: str = Field(description="owner_id")
    creator_id: str = Field(description="creator_id")
    person_id: str = Field(description="person_id")
    email_needs_tickling: bool = Field(description="email_needs_tickling")
    organization_name: str = Field(description="organization_name")
    source: str = Field(description="source")
    original_source: str = Field(description="original_source")
    organization_id: str = Field(description="organization_id")
    headline: str = Field(description="headline")
    photo_url: str = Field(description="photo_url")
    present_raw_address: str = Field(description="present_raw_address")
    linkedin_uid: str = Field(description="linkedin_uid")
    extrapolated_email_confidence: str = Field(description="extrapolated_email_confidence")
    salesforce_id: str = Field(description="salesforce_id")
    salesforce_lead_id: str = Field(description="salesforce_lead_id")
    salesforce_contact_id: str = Field(description="salesforce_contact_id")
    salesforce_account_id: str = Field(description="salesforce_account_id")
    crm_owner_id: str = Field(description="crm_owner_id")
    created_at: str = Field(description="created_at")
    emailer_campaign_ids: List[str] = Field(description="emailer_campaign_ids")
    direct_dial_status: str = Field(description="direct_dial_status")
    direct_dial_enrichment_failed_at: str = Field(description="direct_dial_enrichment_failed_at")
    email_status: str = Field(description="email_status")
    email_source: str = Field(description="email_source")
    account_id: str = Field(description="account_id")
    last_activity_date: str = Field(description="last_activity_date")
    hubspot_vid: str = Field(description="hubspot_vid")
    hubspot_company_id: str = Field(description="hubspot_company_id")
    crm_id: str = Field(description="crm_id")
    sanitized_phone: str = Field(description="sanitized_phone")
    merged_crm_ids: str = Field(description="merged_crm_ids")
    updated_at: str = Field(description="updated_at")
    queued_for_crm_push: bool = Field(description="queued_for_crm_push")
    suggested_from_rule_engine_config_id: str = Field(description="suggested_from_rule_engine_config_id")
    email_unsubscribed: str = Field(description="email_unsubscribed")
    label_ids: List[Any] = Field(description="label_ids")
    has_pending_email_arcgate_request: bool = Field(description="has_pending_email_arcgate_request")
    has_email_arcgate_request: bool = Field(description="has_email_arcgate_request")
    existence_level: str = Field(description="existence_level")
    email: str = Field(description="email")
    email_from_customer: str = Field(description="email_from_customer")
    typed_custom_fields: Dict[str, Any] = Field(description="typed_custom_fields")
    custom_field_errors: Dict[str, Any] = Field(description="custom_field_errors")
    salesforce_record_url: str = Field(description="salesforce_record_url")
    crm_record_url: str = Field(description="crm_record_url")
    email_status_unavailable_reason: str = Field(description="email_status_unavailable_reason")
    email_true_status: str = Field(description="email_true_status")
    updated_email_true_status: bool = Field(description="updated_email_true_status")
    contact_rule_config_statuses: List[Dict[str, Any]] = Field(description="contact_rule_config_statuses")
    source_display_name: str = Field(description="source_display_name")
    twitter_url: str = Field(description="twitter_url")
    contact_campaign_statuses: List[Dict[str, Any]] = Field(description="contact_campaign_statuses")
    state: str = Field(description="state")
    city: str = Field(description="city")
    country: str = Field(description="country")
    account: Account = Field(description="account")
    contact_emails: List[ContactEmail] = Field(description="contact_emails")
    organization: Organization = Field(description="organization")
    employment_history: List[EmploymentHistory] = Field(description="employment_history")
    time_zone: str = Field(description="time_zone")
    intent_strength: str = Field(description="intent_strength")
    show_intent: bool = Field(description="show_intent")
    phone_numbers: List[PhoneNumber] = Field(description="phone_numbers")
    account_phone_note: str = Field(description="account_phone_note")
    free_domain: bool = Field(description="free_domain")
    is_likely_to_engage: bool = Field(description="is_likely_to_engage")
    email_domain_catchall: bool = Field(description="email_domain_catchall")
    contact_job_change_event: str = Field(description="contact_job_change_event")

class Pagination(BaseModel):
    page: int = Field(description="page")
    per_page: int = Field(description="per_page")
    total_entries: int = Field(description="total_entries")
    total_pages: int = Field(description="total_pages")

class PeopleSearchResponse(BaseModel):
    # breadcrumbs: Optional[List[Breadcrumb]] = Field(default=None, description="breadcrumbs")
    partial_results_only: Optional[bool] = Field(default=None, description="partial_results_only")
    has_join: Optional[bool] = Field(default=None, description="has_join")
    disable_eu_prospecting: Optional[bool] = Field(default=None, description="disable_eu_prospecting")
    partial_results_limit: Optional[int] = Field(default=None, description="partial_results_limit")
    pagination: Optional[Pagination] = Field(default=None, description="pagination")
    contacts: Optional[List[Contact]] = Field(default=None, description="contacts")
    people: Optional[List[Any]] = Field(default=None, description="people")
    model_ids: Optional[List[str]] = Field(default=None, description="model_ids")
    num_fetch_result: Optional[str] = Field(default=None, description="num_fetch_result")
    # derived_params: Optional[str] = Field(default=None, description="derived_params")
